//https://hardhat.org/tutorial/deploying-to-a-live-network#_7-deploying-to-a-live-network

const hre=require('hardhat');

async function main(){
    //return list of account addresses
    //if defaultNetwork=hardhat,then list of all accounts generated by hardhat returned else
   //if defaultNetwork=polygon,then accounts defined under polygon are returned
    const [deployer] = await ethers.getSigners(); 

    console.log("Deploying contracts with the account:", deployer.address);
  
    console.log("Account balance:", (await deployer.getBalance()).toString());

    // .getContractFactory("<contract name>") function of ethers.js, used to access contracts in the artifacts folder
    const Dwitter= await hre.ethers.getContractFactory("Dwitter")
    const dwitter= await Dwitter.deploy();

    await dwitter.deployed();

    console.log("Deployed Contract Address: ",dwitter.address);
}

main()
    .then(() => process.exit(0) )
    .catch((error) =>{
        console.log(error)
        process.exit(1);
    })

// run this npx hardhat run scripts/deploy.js
// check deployed contract using
//https://mumbai.polygonscan.com/address/0xc5d009C7F6e6256d2294E0Ad3F208046aB96a036